name: notification-service

services:
  backend:
    image: backend
    build:
      context: ../../../
      dockerfile: src/main/docker/backend/Dockerfile
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongo
