name: notification-service

services:
  webapp:
    image: webapp
    build:
      context: ../../../
      dockerfile: src/main/docker/webapp/Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=host.docker.internal
      - BACKEND_PORT=8080
    volumes:
      - ./webapp/nginx.conf:/etc/nginx/templates/default.conf.template

  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongo
